### PR TITLE
Blog revamp with Publish page

### PR DESCRIPTION
**Pull request by garyanewsome**
###### Blog Revamp
- create a Blog Admin page where posts can be published and unpublish
- link post attachments to the post's `id` so when posts are deleted images are not orphaned
- revamp layout of blog page
- removed unneeded `post_id` field from `posts` table

Removed unneeded/redundant `post_id` field for the `post` table. Assigned the `id` of a post to the `post attachments` preventing orphaned images if a post was deleted. Added a post administraion page that allows for posts to be `Published, Unpublished, or Deleted` the default state is set to `Unpublished`. Finally adjusted the layout of the blog to feature the latest post and shift all posts to an archive list on the right.

###### Needs
- Code Review
- Approval
- Deployed
- More Posts

###### Future Update
- Change the Published and Unpublished buttons to a toggle with Body Snatchers like JS

### CODE REVIEW

**Comment by ninjapanzer** [comment]
NEAT!

**Comment by garyanewsome** [comment]
screen shot 2016-11-07 at 2 25 26 pm

**Comment by ninjapanzer** [comment]
When you create a post it should not have an id yet so you likely have a messed up helper on your form

**Comment by garyanewsome** [comment]
I know you hate boxes and borders, but this could be a nice way to break up the posts on the main page.

screen shot 2016-11-18 at 10 06 10 pm

**Comment by garyanewsome** [comment]
- Posts system is fully functional, including `post_id`.

- Post attachments stores the the attachments, then creates an additional attachment that stores the `post_id`

**Comment by garyanewsome** [comment]
screen shot 2016-11-23 at 12 04 56 pm

**Comment by ninjapanzer** [comment]
@savvysoftworks What do you think ^^^

**Pull request merged**
