### PR TITLE
create unique blog header

### PR DESCRIPTION
**Pull request by garyanewsome**
###### Create Unique Blog Header

our materialize code was conflicting with the blogs materialize code causing the hamburgarler to be open all the time and in the middle of the blog page. I created a separate blog header with only the logo link to the home page. This eliminates the problem,

###### Needs
- code review
- approval
- deployed

### CODE REVIEW

**Comment by ninjapanzer** [comment]
I am not sure this is the direction I want to go right now and will be doing a bisect to see where this problem was introduced. I will update with a linked issue or fix once I discover the commit that introduces the bug

**Comment by ninjapanzer** [comment]
TODO:
- [ ] Finish separating layouts
- [ ] Fix subnav initialization
- [ ] allow app and posts layouts to share headers and footers

screen shot 2017-06-19 at 11 37 47 am
screen shot 2017-06-19 at 11 37 32 am

**Comment by ninjapanzer** [comment]
Last commit looks good @garyanewsome

**Comment by garyanewsome** [comment]
Fixed the indentation on the mobile-nav ul, removes the need for the hack and mobile nav now works on all pages.

**Pull request merged**
